version: '3'

services:
  mongo:
    image: mongo:6.0.5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mgroot
      - MONGO_INITDB_ROOT_PASSWORD=zm2023
   
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mgroot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=zm2023
      - ME_CONFIG_MONGODB_URL=mongodb://mgroot:zm2023@mongo:27017/